#!/usr/bin/env ruby
board_layout = ARGV[0]
my_player = ARGV[1]

class Board
  def initialize(board_layout)
    @layout = board_layout
  end
  
  def next_move
    sum = 0
    @layout.split('').each_with_index do |cell, index|
      num = index + 1
      in_corner = [1, 3, 7, 9].include?(num)
      empty = cell == '.'
      puts in_corner
      puts empty
      puts num
      return coords(num) if in_corner and empty
    end
    '(0,0)'
  end
  
  def coords(num)
    x = (num - 1) % 3
    y = (num - 1) / 3
    "(#{x}, #{y})"
  end
end

board = Board.new(board_layout)
puts board.next_move